version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - rabbitmq
      - mysql
    volumes:
      - ./api/logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=users_db

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Porta para conexão AMQP
      - "15672:15672"  # Porta para interface de gerenciamento do RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  consumer:
    build: ./api
    command: python consumers.py
    depends_on:
      - mongo
      - rabbitmq
      - mysql
    volumes:
      - ./api/logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=users_db

volumes:
  mongo-data:
  mysql-data: